### ISSUE TITLE
[Feature] Support Float

### ISSUE THREAD

**Issue by Ticket-Master** [tomatophp/filament-wallet#2]
I am using Float balances on my laravel app and when i use Wallet action on my filamentphp table then it only saves in integer

I am using HasWalletFloat on my User model and also implements WalletFloat.

Please tell me how can i make this work ?

**Comment by 3x1io** [comment]
we will try to handle it on the next version.

**Comment by 3x1io** [comment]
fixed in Wallet change integer to float #5
