### ISSUE TITLE
Multi-tenancy is not working

### ISSUE THREAD

**Issue by aisuvro** [tomatophp/filament-wallet#4]
Hi There,
It is a great plugin for the single admin panel.
This plugin is not working in the filament's multi-tenancy.

If I add a single line to the resource page of the plugin, it works like a charm.

```php
protected static bool $isScopedToTenant = false;
```
If I extend the resource still it is not working.

```php
<?php

namespace App\Filament\Member\Resources;


use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use TomatoPHP\FilamentWallet\Filament\Resources\WalletResource as TomatoWalletResource;

class WalletResource extends TomatoWalletResource
{
    protected static bool $isScopedToTenant = false;
}

```

**Comment by 3x1io** [comment]
you can extend the Resource and allow scope, and I will add it as an option to allow tenants on all tomato echo system packages.
